### PR TITLE
fix: prevent trimming attempts on undefined value

### LINKED ISSUE #388: Stdout undefined. .trim error.
**🐞 Describe the bug**

Discovered this bug today the first time:

image

### PR DESCRIPTION
**Pull request by asennikov**
Fixes https://github.com/BetaHuhn/deploy-to-vercel-action/issues/388

I'm not sure what is the root cause for the command to return no stdout, but I think the `execCmd` utility should be ready for that situation anyway.

As it currently stands, we have been getting these errors since this morning:

image

### CODE REVIEW

File: dist/index.js [hunk 1]
```diff
@@ -15946,7 +15946,8 @@ const context = {
 	}),
 	ALIAS_DOMAINS: parser.getInput({
 		key: 'ALIAS_DOMAINS',
-		type: 'array'
+		type: 'array',
+		disableable: true
```
Comment (asennikov) [inline dist/index.js:15950]: not sure why this change happened, this is the result of running `npm run build` in the repo.

**Comment by rory-pickering** [comment]
Please merge this 😭

**Review by BetaHuhn — APPROVED** [review]
Thanks @asennikov!
