### PR TITLE
♻️ Use `spawn` instead of `exec` so arguments are escaped

### LINKED ISSUE #75: Commit message `commands` are unescaped
**🐞 Describe the bug**

Running a commit that contains backticks (`), cause the action to fail because the shell seems to try and run what is contained within the backticks.

**📚 To Reproduce**
Create a commit with e.g. the message: Switch to ESM format to remove need on dependency `fsx`

Deploy using this action using default config (no custom options), result:
```
Error: Command failed: vercel -t *** -m "githubCommitAuthorName=Selwyn" -m "githubCommitAuthorLogin=Siilwyn" -m "githubCommitMessage=Switch to ESM format to remove need on dependency `fsx`" -m "githubCommitOrg=voorhoede" -m "githubCommitRepo=life-terra-platform" -m "githubCommitRef=paginate-translations" -m "githubCommitSha=0aa1994f696737ebe462c6fab9931ce937382c5c" -m "githubOrg=voorhoede" -m "githubRepo=life-terra-platform" -m "githubDeployment=1"
/bin/sh: 1: fsx: not found
```

### PR DESCRIPTION
**Pull request by Siilwyn**
Closes #75

### CODE REVIEW

File: src/vercel.js [hunk 1]
```diff
@@ -22,14 +22,14 @@ const init = () => {
 	let deploymentUrl
 
 	const deploy = async (commit) => {
-		let command = `vercel -t ${ VERCEL_TOKEN }`
+		let commandArguments = [`--token=${ VERCEL_TOKEN }`]
```
Comment (Siilwyn) [inline src/vercel.js:25]: Had to look up what `-t` means, longhand seems more descriptive.

File: src/vercel.js [hunk 2]
```diff
@@ -47,25 +47,25 @@ const init = () => {
 			]
 
 			metadata.forEach((item) => {
-				command += ` -m "${ item }"`
+				commandArguments.push(`--meta="${ item }"`)
```
Comment (Siilwyn) [inline src/vercel.js:50]: Shorthand with `=` doesn't work, `-m=bla` but `--meta=bla` does. We can't use a space, `--meta bla` since spawn would be confused by that.

**Comment by BetaHuhn** [comment]
Will test it on the develop branch.
